import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { pluginsTable } from "../lib/db/src/schema/plugins.js";

const WA = "https://wa.me/201005822858";

const plugins = [
  {
    name: "Quiz AI Chat",
    nameAr: "محادثة الذكاء الاصطناعي للاختبار",
    slug: "local_qai",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "AI-Powered",
    categoryAr: "مدعوم بالذكاء الاصطناعي",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Quiz AI Chat plugin for Moodle.`,
    features: ["AI tutor embedded inside every quiz attempt","Per-question hints and explanations via chat","Configurable LLM model and prompt","No grade impact — pure learning support"],
    featuresAr: ["معلم ذكاء اصطناعي مدمج داخل كل محاولة اختبار","تلميحات وشروحات لكل سؤال عبر المحادثة","نموذج LLM وبرومبت قابل للتهيئة","لا تأثير على الدرجات — دعم تعليمي بحت"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Chat with Assignment",
    nameAr: "محادثة مع المهمة",
    slug: "local_chatwithassignment",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "AI-Powered",
    categoryAr: "مدعوم بالذكاء الاصطناعي",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Chat with Assignment plugin for Moodle.`,
    features: ["AI chat on assignment feedback & rubric scores","Students ask follow-up questions on teacher feedback","Configurable LLM and system prompt per assignment","Full Moodle activity integration"],
    featuresAr: ["محادثة ذكاء اصطناعي حول تغذية المهمة ودرجات الروبريك","يطرح الطلاب أسئلة متابعة على تغذية المعلم","LLM وبرومبت نظام قابل للتهيئة لكل مهمة","تكامل كامل مع نشاط Moodle"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Smart Grade AI",
    nameAr: "تصحيح ذكي بالذكاء الاصطناعي",
    slug: "local_smartgradeai",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "AI-Powered",
    categoryAr: "مدعوم بالذكاء الاصطناعي",
    free: true,
    paidSupport: false,
    placeholder: false,
    price: null,
    downloadUrl: "https://moodle.org/plugins/local_smartgradeai",
    requiresSetup: true,
    setupPrice: 100,
    features: ["Human-in-the-loop AI grading with teacher review","Rubric-based scoring via configurable LLM","Batch grade all submissions in one click","n8n workflow integration for AI backend"],
    featuresAr: ["تصحيح ذكاء اصطناعي مع مراجعة المعلم","تسجيل نقاط مستند إلى الروبريك عبر LLM قابل للتهيئة","تصحيح دفعي لجميع التسليمات بنقرة واحدة","تكامل سير عمل n8n للواجهة الخلفية للذكاء الاصطناعي"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "AI Rubric Generator",
    nameAr: "مولّد روبريك بالذكاء الاصطناعي",
    slug: "local_airubricgenerator",
    type: "local",
    moodle: "Moodle 4.5+",
    category: "AI-Powered",
    categoryAr: "مدعوم بالذكاء الاصطناعي",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the AI Rubric Generator plugin for Moodle.`,
    features: ["Generate rubrics with AI from assignment description","Saves directly as a Moodle advanced grading rubric","Configurable LLM model and criteria count","One-click generation inside the assignment settings"],
    featuresAr: ["إنشاء روبريك بالذكاء الاصطناعي من وصف المهمة","يحفظ مباشرةً كروبريك تقييم متقدم في Moodle","نموذج LLM وعدد معايير قابل للتهيئة","إنشاء بنقرة واحدة داخل إعدادات المهمة"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Adaptive Study Plan",
    nameAr: "خطة دراسة تكيفية",
    slug: "mod_adaptiveplan",
    type: "mod",
    moodle: "Moodle 4.0+",
    category: "AI-Powered",
    categoryAr: "مدعوم بالذكاء الاصطناعي",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Adaptive Study Plan plugin for Moodle.`,
    features: ["AI generates personalised weekly study schedules","Onboarding questionnaire for hours & prior knowledge","Dynamic checklists with smart time estimation","AI Chat Coach to renegotiate deadlines on demand"],
    featuresAr: ["الذكاء الاصطناعي يولّد جداول دراسية أسبوعية مخصصة","استبيان تأهيلي للساعات والمعرفة المسبقة","قوائم مهام ديناميكية مع تقدير زمني ذكي","مدرب ذكاء اصطناعي لإعادة التفاوض على المواعيد"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Smart Dashboard",
    nameAr: "لوحة تحكم ذكية",
    slug: "local_smartdashboard",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "Analytics & Reporting",
    categoryAr: "التحليلات والتقارير",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Smart Dashboard plugin for Moodle.`,
    features: ["Custom analytics dashboard for students and teachers","Course progress, grades, and activity overview","Dark-themed, mobile-responsive UI","CSV export for all data sections"],
    featuresAr: ["لوحة تحليلات مخصصة للطلاب والمعلمين","تقدم المقرر والدرجات ونظرة عامة على الأنشطة","واجهة مستخدم داكنة ومتجاوبة مع الجوال","تصدير CSV لجميع أقسام البيانات"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Student Grades Report",
    nameAr: "تقرير درجات الطالب",
    slug: "report_studentgrades",
    type: "report",
    moodle: "Moodle 4.0+",
    category: "Analytics & Reporting",
    categoryAr: "التحليلات والتقارير",
    free: true,
    paidSupport: true,
    placeholder: false,
    price: null,
    downloadUrl: "https://moodle.org/plugins/report_studentgrades",
    features: ["Export all enrolled course grades as one HTML file","Hierarchical grade structure with categories & totals","18+ colour settings, RTL support, Word-compatible output","Students & authorised admins can view cross-course records"],
    featuresAr: ["تصدير جميع درجات المقررات المسجلة كملف HTML واحد","هيكل درجات هرمي مع الفئات والمجاميع","أكثر من 18 إعداد ألوان ودعم RTL وإخراج متوافق مع Word","الطلاب والمسؤولون المخوّلون يمكنهم عرض سجلات متعددة المقررات"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "HTML Grade Export",
    nameAr: "تصدير درجات HTML",
    slug: "gradereport_htmlexport",
    type: "gradereport",
    moodle: "Moodle 4.0+",
    category: "Analytics & Reporting",
    categoryAr: "التحليلات والتقارير",
    free: true,
    paidSupport: false,
    placeholder: false,
    price: null,
    downloadUrl: "https://moodle.org/plugins/gradereport_htmlexport",
    features: ["Per-course grade export as beautifully styled HTML","Bulk ZIP download for all students at once","18+ colour themes, site logo integration, print-ready CSS","GDPR-compliant, full RTL & accessibility support"],
    featuresAr: ["تصدير درجات كل مقرر كـHTML منسق بجمال","تنزيل ZIP جماعي لجميع الطلاب دفعة واحدة","أكثر من 18 ثيم ألوان وتكامل شعار الموقع وCSS جاهز للطباعة","متوافق مع GDPR ودعم كامل لـRTL وإمكانية الوصول"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Gap Close",
    nameAr: "سد الفجوات",
    slug: "mod_gapclose",
    type: "mod",
    moodle: "Moodle 4.0+",
    category: "Course Tools",
    categoryAr: "أدوات المقرر",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Gap Close plugin for Moodle.`,
    features: ["Auto-detects incorrect answers across all course quizzes","Builds a focused review session from the student's gaps","Native Moodle Question Engine with live feedback","Resumable sessions; restart to scan for fresh gaps"],
    featuresAr: ["يكتشف تلقائياً الإجابات الخاطئة في جميع اختبارات المقرر","يبني جلسة مراجعة مركّزة من فجوات الطالب","محرك أسئلة Moodle الأصلي مع تغذية راجعة فورية","جلسات قابلة للاستئناف؛ أعد التشغيل للبحث عن فجوات جديدة"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Protected PDF",
    nameAr: "PDF محمي",
    slug: "mod_protectedpdf",
    type: "mod",
    moodle: "Moodle 3.10+",
    category: "Course Tools",
    categoryAr: "أدوات المقرر",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Protected PDF plugin for Moodle.`,
    features: ["Watermarks every PDF download with student name & email","FPDI-powered per-page overlay on the original file","Access-controlled to enrolled, authenticated users only","Moodle completion tracking & backup/restore support"],
    featuresAr: ["يضع علامة مائية على كل تنزيل PDF باسم الطالب وبريده","تراكب لكل صفحة بواسطة FPDI على الملف الأصلي","وصول محكوم للمستخدمين المسجلين والمصادق عليهم فقط","دعم تتبع الإكمال والنسخ الاحتياطي والاستعادة في Moodle"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Private YouTube",
    nameAr: "يوتيوب خاص",
    slug: "mod_privateyoutube",
    type: "mod",
    moodle: "Moodle 4.0+",
    category: "Course Tools",
    categoryAr: "أدوات المقرر",
    free: false,
    paidSupport: false,
    placeholder: true,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Private YouTube plugin for Moodle.`,
    features: [],
    featuresAr: [],
    images: [],
    description: "Embed unlisted or private YouTube videos in your Moodle courses without exposing the video URL to students. Full Moodle activity integration with completion tracking.",
    descriptionAr: "ضمّن مقاطع YouTube غير المدرجة أو الخاصة في مقررات Moodle دون الكشف عن رابط الفيديو للطلاب. تكامل كامل مع نشاط Moodle وتتبع الإكمال.",
  },
  {
    name: "Smart Catalog",
    nameAr: "كتالوج ذكي",
    slug: "local_smartcatalog",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "Course Tools",
    categoryAr: "أدوات المقرر",
    free: false,
    paidSupport: false,
    placeholder: true,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Smart Catalog plugin for Moodle.`,
    features: [],
    featuresAr: [],
    images: [],
    description: "A beautiful, filterable course catalog for your Moodle platform. Replaces the default course listing with a modern card-based UI, category filters, search, and enrolment calls-to-action.",
    descriptionAr: "كتالوج مقررات جميل وقابل للتصفية لمنصة Moodle الخاصة بك.",
  },
  {
    name: "Credit Enrollment",
    nameAr: "تسجيل بالرصيد",
    slug: "enrol_credit",
    type: "enrol",
    moodle: "Moodle 4.0+",
    category: "Course Tools",
    categoryAr: "أدوات المقرر",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Credit Enrollment plugin for Moodle.`,
    features: ["Students spend a credit balance to enrol in courses","Per-course credit cost configured by admins","Auto-deducted on successful enrolment with balance display","Enrolment keys, periods & max user limits supported"],
    featuresAr: ["يستخدم الطلاب رصيد ائتماني للتسجيل في المقررات","تكلفة الرصيد لكل مقرر تُهيأ من قِبَل المسؤولين","يُخصم تلقائياً عند التسجيل الناجح مع عرض الرصيد","دعم مفاتيح التسجيل والفترات وحدود المستخدمين القصوى"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Custom Home Redirect",
    nameAr: "إعادة توجيه الصفحة الرئيسية",
    slug: "local_customhome",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "Platform & Admin",
    categoryAr: "المنصة والإدارة",
    free: true,
    paidSupport: true,
    placeholder: false,
    price: null,
    downloadUrl: "https://moodle.org/plugins/local_customhome",
    features: ["Replace Moodle front page with any custom URL","Admin bypass — site admins are never locked out","Emergency bypass via ?noredirect=1 query parameter","AI Prompt Generator builds a landing page from live Moodle data"],
    featuresAr: ["استبدال صفحة Moodle الأمامية بأي URL مخصص","تجاوز للمسؤول — لا يُقفَل مسؤولو الموقع أبداً","تجاوز طارئ عبر معامل ?noredirect=1","مولّد البرومبت الذكي يبني صفحة هبوط من بيانات Moodle الحية"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Parent Assign",
    nameAr: "تعيين ولي الأمر",
    slug: "local_parentassign",
    type: "local",
    moodle: "Moodle 4.1+",
    category: "Platform & Admin",
    categoryAr: "المنصة والإدارة",
    free: true,
    paidSupport: false,
    placeholder: false,
    price: null,
    downloadUrl: "https://moodle.org/plugins/local_parentassign",
    features: ["Auto-creates parent accounts from student profile fields","Sends welcome email with temporary credentials","Scheduled task fallback for bulk CSV uploads","Fully implements Moodle's Privacy API"],
    featuresAr: ["إنشاء تلقائي لحسابات ولي الأمر من حقول ملف الطالب","يرسل بريد ترحيب ببيانات اعتماد مؤقتة","مهمة مجدولة احتياطية لتحميلات CSV الجماعية","تطبيق كامل لـPrivacy API في Moodle"],
    images: [],
    description: "",
    descriptionAr: "",
  },
  {
    name: "Quick Login",
    nameAr: "تسجيل دخول سريع",
    slug: "local_qlogin",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "Platform & Admin",
    categoryAr: "المنصة والإدارة",
    free: false,
    paidSupport: false,
    placeholder: true,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Quick Login plugin for Moodle.`,
    features: [],
    featuresAr: [],
    images: [],
    description: "A Moodle plugin for administrators to quickly log in as any user without needing their password. Useful for support and troubleshooting.",
    descriptionAr: "إضافة Moodle للمسؤولين لتسجيل الدخول بسرعة كأي مستخدم دون الحاجة إلى كلمة مروره.",
  },
  {
    name: "Balance Updater",
    nameAr: "محدّث الرصيد",
    slug: "local_balanceupdater",
    type: "local",
    moodle: "Moodle 4.0+",
    category: "Platform & Admin",
    categoryAr: "المنصة والإدارة",
    free: false,
    paidSupport: false,
    placeholder: true,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Balance Updater plugin for Moodle.`,
    features: [],
    featuresAr: [],
    images: [],
    description: "Bulk update student credit balances via CSV upload. Integrates with the Credit Enrollment plugin for automated credit management.",
    descriptionAr: "تحديث جماعي لأرصدة الائتمان عبر CSV. يتكامل مع إضافة التسجيل بالرصيد.",
  },
  {
    name: "Kashier Payment Gateway",
    nameAr: "بوابة دفع كاشير",
    slug: "paygw_kashier",
    type: "paygw",
    moodle: "Moodle 4.0+",
    category: "Platform & Admin",
    categoryAr: "المنصة والإدارة",
    free: false,
    paidSupport: false,
    placeholder: false,
    price: 50,
    buyUrl: `${WA}?text=Hi! I'm interested in the Kashier Payment Gateway plugin for Moodle.`,
    features: ["Kashier payment gateway for Moodle enrolment","Supports Egyptian EGP and major currencies","Full Moodle Payment API integration","Webhook-based payment confirmation"],
    featuresAr: ["بوابة دفع كاشير لتسجيل Moodle","تدعم الجنيه المصري والعملات الرئيسية","تكامل كامل مع Payment API في Moodle","تأكيد الدفع عبر Webhook"],
    images: [],
    description: "",
    descriptionAr: "",
  },
];

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema: { pluginsTable } });

async function seed() {
  console.log("Seeding plugins...");
  for (const p of plugins) {
    await db
      .insert(pluginsTable)
      .values(p as any)
      .onConflictDoUpdate({
        target: pluginsTable.slug,
        set: { ...p, updatedAt: new Date() } as any,
      });
    console.log(`  ✓ ${p.name}`);
  }
  console.log(`Done! ${plugins.length} plugins seeded.`);
  await pool.end();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
